# Generated by Django 2.0.7 on 2020-04-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200331_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='lang',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(blank=True, choices=[('<p>', 'Paragraph'), ('<li>', 'List'), ('<object>', 'Object'), ('<span>', 'Span Block'), ('<div>', 'Div Block')], max_length=10),
        ),
    ]
