# Generated by Django 2.0.7 on 2020-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200411_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Francais'), ('pt', 'Portugues')], max_length=2),
        ),
    ]
